### ISSUE TITLE
How can we specify the collapse option in table2itol.R

### ISSUE THREAD

**Issue by SilasK** [mgoeker/table2itol#1]
Thank you @mgoeker  for your great tool! 
I have a binary collum in my table and it gets converted to a binary itol file. how can I select the alternative collapse format?

Is it possible to collapse different clades that are not connected in the same run?

**Comment by mgoeker** [comment]
On 06.02.20 08:47, Silas Kieser wrote:
> Thank you @mgoeker <https://github.com/mgoeker> for your great tool!
> I have a binary collum in my table and it gets converted to a binary 
> itol file. how can I select the alternative collapse format?
> 
> Is it possible to collapse different clades that are not connected in 
> the same run?

Sorry for the delayed response. I have created a section "How can I 
generate iTOL instructions for collapsing subtrees?" in the README which 
hopefully covers this topic.

It should be possible to generate collapsing instructions for several 
clades in a single run by using an according logical vector.

**Comment by SilasK** [comment]
Great, thank you. 
could I ask you to explain a bit better how the `identifier2` could be used to generate other branch annotations? 

Can I add labels for genus, family .. clades?  

By the way, your documentation is much more informative that the one on itol.

**Comment by mgoeker** [comment]
On 02.03.20 10:01, Silas Kieser wrote:
> Great, thank you.
> could I ask you to explain a bit better how the |identifier2| could be 
> used to generate other branch annotations?
> 
> Can I add labels for genus, family .. clades?
> 
> By the way, your documentation is much more informative that the one on 
> itol.

I've added the following text to the FAQ entry:

"
The tests/INPUT folder contains an example file for specifying branch 
annotations. While --identifier must not be NA, --identifier2 can be NA. 
The pair of identifiers then specifies a tip, literally provided in the 
--identifier column. If both --identifier and --identifier2 are not NA 
the pair specifies a branch.
"

The file I am referring to is tests/INPUT/branch_annotation_1.tsv. It 
contain a column "Collapse 1" with a logical vector. This column yields 
the file tests/E006/iTOL_collapse-Collapse_1.txt if you run the tests. 
This file contains iTOL collapsing instructions.
