### ISSUE TITLE
How to generate a annotation file of the specified type

### ISSUE THREAD

**Issue by Pengying-Wang** [mgoeker/table2itol#2]
Thank you for developing a good tool. But I have a question. Because there are many kinds in some of my annotation information, using this package will automatically generate a "domain" type annotation file, and what I want is a "colorstrip" type annotation file, and I didn't find a way to use this R package to generate annotation files of the specified type. So how can I generate a annotation file of the specified type. Thanks for your time and kind help!

**Comment by mgoeker** [comment]
Thanks for your interest in table2itol. The scripts uses domains instead 
of colorstrips when it assumes that there are too many colours to be 
easily distinguishable by eye. This behaviour can be modified using 
--max-size (-m) option. If you lower that value, table2itol should more 
frequently switch to colorstrip output.

**Comment by Pengying-Wang** [comment]
Thank you so much!
And if I use&nbsp;create_itol_files() in R rather than Liunx, what parameter should I use? Well, which parameter is same with --max-size (-m) in&nbsp;create_itol_files() ？
Really appreciated for your help！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"mgoeker"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月6日(星期三) 晚上9:46
收件人:&nbsp;"mgoeker/table2itol"<table2itol@noreply.github.com&gt;;
抄送:&nbsp;"Noodles"<739324017@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mgoeker/table2itol] How to generate a annotation file of the specified type (#2)





 Thanks for your interest in table2itol. The scripts uses domains instead 
 of colorstrips when it assumes that there are too many colours to be 
 easily distinguishable by eye. This behaviour can be modified using 
 --max-size (-m) option. If you lower that value, table2itol should more 
 frequently switch to colorstrip output.

**Comment by Pengying-Wang** [comment]
I found&nbsp;max.size = 20L, and I used&nbsp;max.size = 200L, but there is this wrong information:

So, could you please help me how to solve this?


Thank you so much!






------------------ 原始邮件 ------------------
发件人:&nbsp;"mgoeker"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月6日(星期三) 晚上9:46
收件人:&nbsp;"mgoeker/table2itol"<table2itol@noreply.github.com&gt;;
抄送:&nbsp;"Noodles"<739324017@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mgoeker/table2itol] How to generate a annotation file of the specified type (#2)





 Thanks for your interest in table2itol. The scripts uses domains instead 
 of colorstrips when it assumes that there are too many colours to be 
 easily distinguishable by eye. This behaviour can be modified using 
 --max-size (-m) option. If you lower that value, table2itol should more 
 frequently switch to colorstrip output.

**Comment by mgoeker** [comment]
On 06.05.20 16:28, CupwineGreentea wrote:
> I found&nbsp;max.size = 20L, and I used&nbsp;max.size = 200L, but there 
> is this wrong information:
> 
> So, could you please help me how to solve this?

I think if you want a colorstrip you should lower the value of max.size.

The relationship between the command-line options and the function 
arguments is 1:1, for a brief explanation see the 
https://github.com/mgoeker/table2itol/#interactive-use section use of 
the README.
